[versions]
dokka = "2.1.0"
javax = "1"
objenesis = "3.5"
lorem = "2.2"
jupiter = "6.0.3"
mockk = "1.14.6"
kotlin = "2.0.0"
kotlinter = "5.2.0"
detekt = "1.23.8"
kover = "0.9.7"
vanniktech = "0.35.0"

[libraries]
objenesis = { module = "org.objenesis:objenesis", version.ref = "objenesis" }
lorem = { module = "com.thedeanda:lorem", version.ref = "lorem" }

inject = { module = "javax.inject:javax.inject", version.ref = "javax" }

junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }
mockK = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
vanniktech = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
